### PR TITLE
Support for image purging and multiple URL's per line.

### PR DESCRIPTION
**Pull request by dancingplatypus**
Added the following capabilities:
1. The boolean option, `deleteAfterEncoding`, can be set to true to delete images that are successfully encoded into the style sheet.
2. Multiple URL's can be encoded, whether or not they appear on the same line.
3. `/*ImageEmbed:skip*/` must now appear after the trailing parentheses of `url(...)`, and before any punctuation.  whitespace is permitted in or around the comment tag.  I made this change because a semicolon is not syntactically guaranteed to appear.  The `@font-face` declaration is my empirical example.
4. (aesthetic) Shortened some of the log messages to fit within my command window.
5. Updated Readme.md (although the new requirements for skip might need to be spelled out).

### CODE REVIEW

**Comment by ehynds** [comment]
Hey, I'm testing this out but I get an error encoding a stylesheet with a line that looks like:

`background-image: url('../images/test.png'); background-image: url('../images/test.png');`

<WARN> /Users/ehynds/Dropbox/Projects/grunt-image-embed/tasks../images/test.png); background-image: url(../images/test.png does not exist Use --force to continue. </WARN>

The same declaration works fine on a line by itself. Can you advise?

**Comment by dancingplatypus** [comment]
I will take a look at this tomorrow.  lint is complaining about some things
I've done, so I'll make that work, as well as getting it working in your
test framework, including your specific issue.

Thanks for being patient with me.  I'm learning a lot about grunt and unit
testing through this exercise.

**Comment by dancingplatypus** [comment]
I've pushed a new version to my fork.  It now passes lint, and I broke out
and added several tests.  I saw that you had a large css with lots of
different tests within, and then I saw your todo comment, so I started
breaking out discrete tests.  It can always use more.

Anyway, if you look inside "test_css_encoder.js" at line 55, you'll see
I've added a test addressing your specific issue.  Perhaps it was my fixes
to make the code lint compliant, but this test passes just fine.  I used
the "../" approach, as well as single quotes, to mimic what you gave me as
closely as I could.

On another issue... "http://www.placehold.it" is problematic.  However they
dynamically generate their images, it is slightly different now and then.
 I included a file, "sanity_check.html" with results across several minutes
of testing.  They are almost identical, but different enough to throw off
the test.  Which sucks.

Please check it out and tell me if there is anything missing, or if you are
still having issues.

Thanks!
Michael Hays

**Comment by ehynds** [comment]
Thanks, I merged her in. Although I just noticed that all tests in test_css_encoder.js are failing. Can you take a look?

**Comment by ehynds** [comment]
It doesn't seem to like external images in the `example/` folder. Try running `grunt` inside there, the outputted CSS file has the two external images removed.

**Comment by dancingplatypus** [comment]
Cool -- I'll check on these tests.  Thanks for the merge.

**Comment by dancingplatypus** [comment]
I modified the regular expression to allow the skip comment to appear
before or after the punctuation.  The examples now work.

**Pull request merged**
